import { cp, rm, mkdir } from 'node:fs/promises'

// dist/ is the deployable, and the spatial study is served inside it as the page
// the demo hands over to. spatial/ stays the single source: this copy is
// regenerated by the build and must never be edited in place. Its dev server,
// tests, README and logs are not part of the deployed study.
const published = ['index.html', 'style.css', 'src', 'vendor']
const root = new URL('../', import.meta.url)
const destination = new URL('dist/spatial/', root)

await rm(destination, { recursive: true, force: true })
await mkdir(destination, { recursive: true })
for (const entry of published) {
  await cp(new URL(`spatial/${entry}`, root), new URL(entry, destination), { recursive: true })
}
console.log(`Synced ${published.join(', ')} to dist/spatial/`)
