// A curated concept graph. Relevance belongs to the selected goal, not to a topic itself.
export const samplePrompt = 'I’m in 6th grade. I want to become an AI researcher. How do I get from here to understanding reinforcement learning?';
const part = (id, weight, relevant = true) => ({ id, weight, relevant });
const leaf = (title, description, connection, example, symbol = '·') => ({ title, description, connection, example, symbol });

export const concepts = {
  rl: { title: 'Reinforcement learning', short: 'Reinforcement learning', symbol: 'λ', description: 'How machines learn to make better decisions.', connection: 'An agent tries an action, receives feedback, and gradually improves its strategy. These connected areas give you a way into the idea.', example: 'Imagine teaching a small robot to navigate a maze. It learns which choices lead it closer to the exit.', children: [part('linear', 25), part('probability', 21), part('calculus', 18), part('python', 16), part('essentials', 20)] },
  linear: { title: 'Linear algebra', symbol: '⌘', description: 'The language of spaces, shapes, and many numbers at once.', connection: 'An AI sees the world as numbers. Linear algebra lets it represent a situation, compare possibilities, and transform information.', example: 'A game state can be a vector: your position, your speed, and the distance to a goal.', children: [part('vectors', 26), part('matrices', 26), part('dot', 19), part('systems', 16), part('eigen', 13, false)] },
  vectors: { title: 'Vectors', symbol: '↗', description: 'A handful of numbers that describe a whole situation.', connection: 'Vectors turn observations into a form an agent can reason about. They are one of the simplest bridges from familiar math into AI.', example: '[3, 5] can describe a position. [3, 5, 2] might add the speed of a moving robot.', children: [part('coordinates', 27), part('arithmetic', 26), part('magnitude', 26), part('proofs', 21, false)] },
  coordinates: leaf('Coordinates', 'Give a position a precise address.', 'Coordinates are a starting point for understanding what the numbers in a vector represent.', 'On a grid, (3, 5) means three steps across and five steps up.', '⌖'),
  arithmetic: leaf('Adding & scaling', 'Move vectors together, or make them larger.', 'Adding combines information. Scaling changes how strongly a piece of information contributes.', '[2, 1] + [1, 3] = [3, 4]. Two small moves become one combined move.', '+'),
  magnitude: leaf('Size & direction', 'Understand how far, and which way.', 'An agent often needs to compare the distance and direction between its current state and its destination.', 'A vector is an arrow: its length is magnitude, and its angle tells you direction.', '↗'),
  proofs: leaf('Abstract vector spaces', 'Explore the formal rules behind vector spaces.', 'This belongs to a deeper study of linear algebra. You can leave it for later in this introductory reinforcement-learning path.', 'The same rules that work for arrows can also describe collections of functions.', 'V'),
  matrices: { title: 'Matrices', symbol: '▦', description: 'Organized grids of numbers that transform information.', connection: 'Matrices let AI systems process many inputs together. They make repeated calculations concise and efficient.', example: 'A matrix can rotate every point in a picture, or combine many input features into predictions.', children: [part('rows', 25), part('multiply', 30), part('transforms', 28), part('determinant', 17, false)] },
  rows: leaf('Rows & columns', 'Read the structure of a grid of numbers.', 'Matrix shapes tell you which calculations can fit together.', 'A 2 × 3 matrix has two rows and three columns.', '▦'),
  multiply: leaf('Multiplication', 'Combine grids using a consistent rule.', 'Matrix multiplication connects layers of calculations in machine learning.', 'Each output combines one row with one column.', '×'),
  transforms: leaf('Transformations', 'See how numbers move and reshape a space.', 'Transformations make matrix operations easier to understand visually.', 'Stretch a square horizontally. The same matrix moves each of its four corners.', '◇'),
  determinant: leaf('Determinants', 'Measure how a transformation scales space.', 'A useful idea in the wider subject, but outside this first path into reinforcement learning.', 'A determinant of two means an area becomes twice as large.', 'Δ'),
  dot: leaf('Dot products', 'Measure how two sets of numbers align.', 'A weighted score is a dot product. It helps a model combine features into one useful estimate.', '[2, 3] · [4, 1] = 11. Multiply matching values, then add.', '·'),
  systems: { title: 'Equations', symbol: '=', description: 'Find values that make several relationships true together.', connection: 'Equations describe relationships between an agent’s states, choices, and expected outcomes.', example: 'Two rules about the same unknown values can help you solve both.', children: [part('variables', 34), part('balance', 34), part('substitute', 32)] },
  variables: leaf('Variables', 'Give an unknown quantity a name.', 'Variables let you describe a relationship before you know every number.', 'If x is your score, x + 5 is your score after a reward.', 'x'),
  balance: leaf('Equality', 'Keep the two sides of an equation balanced.', 'This is the foundation for rearranging equations without changing their meaning.', 'If x + 3 = 8, subtract three from both sides to find x = 5.', '='),
  substitute: leaf('Substitution', 'Replace a name with what it stands for.', 'Substitution connects simple relationships into more complex calculations.', 'If y = 2x and x = 3, then y = 6.', '⇄'),
  eigen: leaf('Eigenvalues', 'Find the special directions a transformation preserves.', 'Eigenvalues are valuable in advanced methods. They are not needed for the introductory RL example shown here.', 'Some arrows keep pointing in the same direction after a transformation; only their lengths change.', 'λ'),
  probability: { title: 'Probability', symbol: 'P', description: 'A way to think clearly about uncertainty.', connection: 'The same action can have different outcomes. Probability helps an agent reason about what might happen next.', example: 'An action might earn a reward 7 times out of 10. How should that affect your next choice?', children: [part('fractions', 22), part('chance', 25), part('expectation', 30), part('distributions', 23)] },
  fractions: leaf('Fractions & ratios', 'Compare parts with a whole.', 'Probabilities use fractions, decimals, and percentages to describe chances.', 'Three successes in four attempts is 3/4, or 75%.', '½'),
  chance: leaf('Chance & events', 'Describe which outcomes are possible.', 'Events let us assign chances to the things an agent observes.', 'Rolling a six is one event with a one-in-six chance on a fair die.', '?'),
  expectation: leaf('Expected value', 'Estimate the average result across many attempts.', 'An agent compares choices by the rewards they might produce over time.', 'A 50% chance of winning 10 points has an expected reward of 5 points.', 'E'),
  distributions: leaf('Distributions', 'See a whole pattern of possible outcomes.', 'A distribution describes more than a single guess: it represents the spread of what could happen.', 'A histogram of 100 game scores shows both typical results and unusual ones.', '∿'),
  calculus: { title: 'Calculus', symbol: '∂', description: 'The mathematics of small changes.', connection: 'For gradient-based methods, calculus reveals which small changes improve a model’s predictions or decisions.', example: 'Imagine standing on a hill. The slope tells you which way to move to go downhill.', children: [part('functions', 28), part('slopes', 28), part('gradients', 28), part('integrals', 16, false)] },
  functions: leaf('Functions', 'Connect an input to an output.', 'A model is a kind of function. It maps information about a situation to a prediction or action.', 'f(x) = 2x turns 3 into 6.', 'f'),
  slopes: leaf('Rates of change', 'See how fast one quantity changes with another.', 'A rate of change helps you understand whether a small adjustment will make a result better or worse.', 'If your distance increases by two meters each second, that rate is your speed.', '↗'),
  gradients: leaf('Gradients', 'Find the direction of change across many inputs.', 'Gradients help train models with many adjustable values.', 'On a landscape, the gradient points toward the steepest uphill direction.', '∇'),
  integrals: leaf('Integration', 'Add up small pieces to understand a whole.', 'Part of the broader subject of calculus, but not required for the example path shown here.', 'Adding many thin strips gives the area underneath a curve.', '∫'),
  python: { title: 'Python', symbol: '</>', description: 'Turn ideas into experiments you can run.', connection: 'Programming gives you a way to build an agent, observe its behavior, and change the rules of its environment.', example: 'Write a tiny maze, give your agent a reward for reaching the exit, and watch its strategy change.', children: [part('code-values', 26), part('loops', 26), part('arrays', 27), part('classes', 21, false)] },
  'code-values': leaf('Values & variables', 'Store information and give it a name.', 'A program needs to remember its position, choices, and rewards.', 'reward = 10 stores a reward you can use in a later calculation.', 'x'),
  loops: leaf('Loops & decisions', 'Repeat actions and choose what happens next.', 'Learning happens over repeated attempts. Loops make these experiments possible.', 'Repeat: choose an action, take a step, record the reward.', '↻'),
  arrays: leaf('Arrays', 'Work with many values as one collection.', 'Arrays store observations, actions, and model parameters efficiently.', 'positions = [2, 4, 7] holds three values you can process together.', '[]'),
  classes: leaf('Classes & objects', 'Organize larger programs into reusable pieces.', 'Helpful when building bigger systems, but optional for a first small RL experiment.', 'An Agent object could hold its position and its strategy.', '{}'),
  essentials: { title: 'RL essentials', symbol: '↻', description: 'The ideas that make reinforcement learning its own field.', connection: 'These are the concepts specific to the learning loop. They connect the supporting math and code to an agent that improves through experience.', example: 'Try → observe → learn → try again. The feedback changes the next decision.', children: [part('agent', 23), part('rewards', 24), part('policies', 27), part('exploration', 26)] },
  agent: leaf('Agent & environment', 'Separate the decision-maker from the world it acts in.', 'An agent observes an environment, takes actions, and receives feedback.', 'A game-playing agent chooses moves. The game is its environment.', '◉'),
  rewards: leaf('Rewards', 'Define the feedback that guides learning.', 'Rewards communicate which outcomes the agent should seek.', 'Reaching an exit gives +10; taking another step costs −1.', '+'),
  policies: leaf('Policies & value', 'Choose a strategy and estimate what a choice is worth.', 'A policy selects actions. Value estimates help compare the long-term consequences of those actions.', 'A move with no immediate reward may still lead to a much better outcome later.', 'π'),
  exploration: leaf('Explore or exploit', 'Balance new possibilities with proven choices.', 'An agent needs to discover useful actions without ignoring what it has already learned.', 'Try a new route sometimes. Use the best known route the rest of the time.', '⤢')
};

export function selectGoal(prompt) {
  if (/reinforcement|\bRL\b|\bAI\b|artificial intelligence|research|machine learning|trial and error/i.test(prompt)) return { id: 'rl', supported: true };
  if (/linear algebra|\bvectors?\b|matri(?:x|ces)/i.test(prompt)) return { id: 'linear', supported: true };
  if (/python|programming|coding/i.test(prompt)) return { id: 'python', supported: true };
  return { id: 'rl', supported: false };
}

export function descendants(id) {
  const seen = new Set();
  function walk(key) { for (const child of concepts[key].children || []) { if (!seen.has(child.id)) { seen.add(child.id); walk(child.id); } } }
  walk(id);
  return seen.size;
}
